### PR TITLE
Don't error in recently killed buffers

### PR DESCRIPTION
**Pull request by nbfalcon**
Drop `flyspell-lazy-buffer-list` since it only increases complexity and is
redundant with `flyspell-lazy-local`. In `flyspell-lazy-checkable-buffer-p`
check if the buffer is live, fixing errors if buffers killed before the idle
timer is run (the main point of this PR).

I ran into this issue when creating a pullrequest using `forge`, after
`forge-post-submit`.

----

#

### CODE REVIEW

**Comment by rolandwalker** [comment]
Hi!  Thanks!

Then the `'kill-buffer-hook` is not needed either, right?

**Comment by nbfalcon** [comment]
The `kill-buffer-hook` is still necessary, because otherwise we would leak timers. Now I am confused why this issue even occurs, though...

**Comment by nbfalcon** [comment]
Okay, I just realized the problem: the `kill-buffer-hook` doesn't remove the timers. It looks like we are leaking timers in general. Do you want me to make a seperate PR to address that, or to do it here? It is an orthogonal change, and this PR is already an improvement.

**Comment by rolandwalker** [comment]
Let's try separate PRs.

**Pull request merged**
